name: Greeting-on-pull-or-issue

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
     steps:
     - uses: actions/first-interaction@v1
     with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
       issue-message: 'That is your first issue. Well Done.'
       pr-message: '# Your first pull request. Well Done'
